### ISSUE TITLE
Strange screen when ssh to running vps

### ISSUE THREAD

**Issue by Sy3Omda** [hahwul/dalfox#104]
Hi, 
I'm facing strange screen when login to my vps via ssh and it's running dalfox like following 
![IMG_20200827_152442](https://user-images.githubusercontent.com/48482029/91448362-0e317d80-e87a-11ea-835f-071c4fef8f56.jpg)

**Comment by hahwul** [comment]
Hi, @Sy3Omda 
Thank you for the issue report. I'll look into it :D

**Comment by hahwul** [comment]
First of all, I am reproduced the same. let's debug on logging code.
![1414](https://user-images.githubusercontent.com/13212227/91472796-ede1dd00-e8d2-11ea-83bc-b0c230a66145.gif)

**Comment by hahwul** [comment]
Hi @Sy3Omda ,
I think it's only reproduced in certain circumstances. First of all, I have been solved in my case, so please check after updating to the latest version. And this seems to be a problem on the spinner side, so I added --no-spinner option!

![1414](https://user-images.githubusercontent.com/13212227/92397645-22228c80-f162-11ea-8ce9-1568ee717cda.gif)

How to update?
- from the source
```
$ go get -u github.com/hahwul/dalfox
```
- from the release
  (It will be release in `2.1.0`, and will be released today or tomorrow. When released, I will leave additional comments)

linux(snapcraft)
```
$ sudo snap refresh dalfox
```

mac
```
$ brew upgrade dalfox
```

**Comment by hahwul** [comment]
e.g
```
$ dalfox url http://testphp.vulnweb.com/listproducts.php\?cat\=123 --no-spinner
```

**Comment by Sy3Omda** [comment]
Yup working like charm.
Btw if you can set this option as default, would be great.

**Comment by hahwul** [comment]
@Sy3Omda 
Unfortunately, that seems difficult. There are too many people using spinner. Because you can know the full URL and the current URL, the total number of queries and the remaining queries.

Let me know if this option doesn't solve the problem! 
Ah, and 2.1.0 has just been released!

**Comment by Sy3Omda** [comment]
Okay fine, I'm gonna close this as it resolved
