### ISSUE TITLE
Version management

### ISSUE THREAD

**Issue by ghost** [hahwul/dalfox#116]
Hi,

do you know whether it's possible to install specific version of Dalfox using brew on Linux (for instance even older ones so we can test and compare)? I tried following some hints using the search engine like always, but haven't been fortunate.

Thanks!

**Comment by hahwul** [comment]
Hi @ZB83486 
Brew by default avoids installing the latest version of the package. Of course, package developers can support the installation by version through separate settings, but they say it's complicated. so Dalfox is also not available for select of version when installing brew is installed now.

There are two ways to install a specific version.

## docker image (https://hub.docker.com/r/hahwul/dalfox/tags)
```
$ docker pull hahwul/dalfox:v2.1.2
$ docker run hahwul/dalfox:v2.1.2
```

## release file install (https://github.com/hahwul/dalfox/tags)
1) Download a specific version of DalFox (for your OS)
2) unzip archive and copy bin file
```
$ unzip dalfox_2.1.2_darwin_amd64.tar.gz
```
```
$ cd dalfox_2.1.2_darwin_amd64
$ cp dalfox /bin/  (your command directory)
```
