### ISSUE TITLE
Tool Crashing

### ISSUE THREAD

**Issue by johnjhacking** [hahwul/dalfox#123]
**Possible Bug?**
I keep having the tool crash on URL lists and i'm unsure how I can fix this:

`goroutine 1 [running]:
github.com/hahwul/dalfox/pkg/optimization.MakeURLEncodeRequestQuery(0xc000032930, 0x65, 0xc001f8c6c0, 0x15, 0xc0084ccff0, 0x26, 0xc003a9e10b, 0x10, 0x0, 0x0, ...)
	/home/planetxort/go/src/github.com/hahwul/dalfox/pkg/optimization/optimization.go:179 +0x9cc
github.com/hahwul/dalfox/pkg/scanning.Scan(0xc000032930, 0x65, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/planetxort/go/src/github.com/hahwul/dalfox/pkg/scanning/scan.go:234 +0x1b1f
github.com/hahwul/dalfox/cmd.glob..func2(0x1945220, 0xc0003b4380, 0x0, 0x2)
	/home/planetxort/go/src/github.com/hahwul/dalfox/cmd/pipe.go:50 +0x457
github.com/spf13/cobra.(*Command).execute(0x1945220, 0xc0003b4360, 0x2, 0x2, 0x1945220, 0xc0003b4360)
	/home/planetxort/go/src/github.com/spf13/cobra/command.go:854 +0x2ae
github.com/spf13/cobra.(*Command).ExecuteC(0x19454c0, 0xc0001a5f68, 0x989b3e, 0x19454c0)
	/home/planetxort/go/src/github.com/spf13/cobra/command.go:958 +0x34a
github.com/spf13/cobra.(*Command).Execute(...)
	/home/planetxort/go/src/github.com/spf13/cobra/command.go:895
github.com/hahwul/dalfox/cmd.Execute()
	/home/planetxort/go/src/github.com/hahwul/dalfox/cmd/root.go:34 +0x32
main.main()
	/home/planetxort/go/src/github.com/hahwul/dalfox/dalfox.go:10 +0x20
`

**Comment by johnjhacking** [comment]
Hello!

Dalfox, latest
Commands attempted:
`cat foo.txt | dalfox pipe > vulns.txt`
`dalfox file foo.txt`
`cat foo.txt | dalfox pipe`

Running Kali Linux, latest.

**Comment by johnjhacking** [comment]
File has a list, one line each of urls:

**Comment by hahwul** [comment]
@johnjhacking 
Is it the version installed using `go-get`? In the case of go get, there is a possibility that errors may occur as a result of committing to the development version. 

I had a similar error during the previous commit, and it could be a related problem.

First, please update now to the latest and test it. 

```
$ go get -u github.com/hahwul/dalfox
```

cc) @bp0lr

**Comment by bp0lr** [comment]
Hi @johnjhacking,

if after update the project you keep having a crash, can you tell me:

1) This happens always in the same url/point?
2) can you share the url causing the crash.

thanks!

**Comment by johnjhacking** [comment]
After updating, I am now getting a brand new error:

not running Get www.example.com: unsupported protocol scheme ""

**Comment by bp0lr** [comment]
@johnjhacking 
that for sure because you are doing passing the url parameter without the scheme.
ex: www.example.com
you need to pass the url parameter using http:// or https://

let me know.

**Comment by johnjhacking** [comment]
Thanks!

**Comment by ChillVibesMushroom** [comment]
./dalfox url https://www.testphp.vulnweb.com --custom-payload=/home/kali/alert.js

not running Get "https://www.testphp.vulnweb.com": dial tcp: lookup www.testphp.vulnweb.com on 192.168.1.1:53: no such host

how would I fix this?

**Comment by hahwul** [comment]
Hi, @ChillVibesMushroom 
I think the host's address is unknown just by looking at the contents you sent. 
Is it possible to query the domain on the PC you are scanning?

```bash
nslookup <YOUR_TARGET>
# or 
ping <YOUR_TARGET>
```

If the test was conducted as you demonstrated, the results you showed would have been displayed because the domain(`www.vulnweb.com` or `www.testphp.vulnweb.com`) doesn't exist. 

> Just in case, I left a comment. alive domain: http://testphp.vulnweb.com/
