### ISSUE TITLE
How to Solve "Segmentation fault" 

### ISSUE THREAD

**Issue by d4715** [hahwul/dalfox#130]
Hello ,
first thanks for create an awesome tool
 
i have trouble with this awesome tool 

i used dalfox version 2.1.1 (shown in image no : 1)
![1](https://user-images.githubusercontent.com/11803332/96122041-8c231400-0f0e-11eb-84a6-0888699cb57d.JPG)

then today i just download latest release of dalfox from 
https://github.com/hahwul/dalfox/releases/tag/v2.2.0

i download this dalfox_2.2.0_freebsd_amd64.tar.gz and save it on my Desktop 
then i extract this tar.gz file and open via terminal 

in terminal i typed cp dalfox /root/go/bin that's mean new dalfox file copy in bin folder of go.
(shown in image no : 2)
![2](https://user-images.githubusercontent.com/11803332/96122058-934a2200-0f0e-11eb-90f4-964796b8f389.JPG)

after copied new file of dalfox then open terminal i typed dalfox version to check new version of dalfox
and i got  Segmentation fault (shown in image no : 3)
![3](https://user-images.githubusercontent.com/11803332/96122080-98a76c80-0f0e-11eb-94cc-9f2ce942bf5e.JPG)

after this show Segmentation fault error i used this command:> root@kali:~/go/bin# go build dalfox
i got this message 
cannot find package "dalfox" in any of:
        /usr/lib/go-1.15/src/dalfox (from $GOROOT)
        /root/go/src/dalfox (from $GOPATH)
(shown in image no : 4)
![4](https://user-images.githubusercontent.com/11803332/96122108-a230d480-0f0e-11eb-9e89-e4e9ab645a84.JPG)

 i want to resolve this issue so i used this command :> root@kali:~/go/bin# go build 
 and i got this reply :> package .: no Go files in /root/go/bin
(show in image no : 5)
![5](https://user-images.githubusercontent.com/11803332/96122122-a8bf4c00-0f0e-11eb-8aaa-4e0cd132bb94.JPG)

this is my kali linux details: (i am using kali linux in a vmware)
root@kali:~# cat /etc/*release
PRETTY_NAME="Kali GNU/Linux Rolling"
NAME="Kali GNU/Linux"
ID=kali
VERSION="2020.3"
VERSION_ID="2020.3"
VERSION_CODENAME="kali-rolling"
ID_LIKE=debian
ANSI_COLOR="1;31"
HOME_URL="https://www.kali.org/"
SUPPORT_URL="https://forums.kali.org/"
BUG_REPORT_URL="https://bugs.kali.org/"

on today (15-10-2020) i update and upgrade kali linux.

so please help me how can i solve this issue.
I am waiting for your valuable reply.
Thanks,
d4715

**Comment by hahwul** [comment]
Hi @d4715 
Thank you for submit issue!

I guess it's an issue caused by the mismatch between the binary architecture and the OS architecture. I remember kali as amd64, is it an OS version compiled separately for freebsd? 

First of all, there are two solutions that I can suggest. 

1) Change binaries 
https://github.com/hahwul/dalfox/releases/download/v2.2.0/dalfox_2.2.0_linux_amd64.tar.gz

2) install from go-get or go build
2-1) using go-get
```
$ go get -u github.com/hahwul/dalfox
$ ~/go/bin/dalfox
```

2-2) using install from source
- case go build
```
$ git clone https://github.com/hahwul/dalfox
$ cd dalfox
$ go build 
$ ./dalfox
```
- case go install
```
$ git clone https://github.com/hahwul/dalfox
$ cd dalfox
$ go install
$ ~/go/bin/dalfox
```

And I can give you an accurate solution with reproducing the problem. I'll test it in a similar environment using docker. Consider it done :D

**Comment by hahwul** [comment]
## Testing log
1) pulling kali image
```
$ docker pull kalilinux/kali
```

2) open image
```
$ docker run -it f5290fd2774e bash
```
3) apt update and install wget
```
$ apt update
$ apt install wget
```
4) download dalfox freebsd-amd64 version and extract
```
$ wget https://github.com/hahwul/dalfox/releases/download/v2.2.0/dalfox_2.2.0_freebsd_amd64.tar.gz
$ tar -xvf dalfox_2.2.0_freebsd_amd64.tar.gz
```
5) run dalfox (freebsd_amd64)
```
$ ./dalfox version
Segmentation fault
```
6) download dalfox linux-amd64 version and extract
```
$ wget https://github.com/hahwul/dalfox/releases/download/v2.2.0/dalfox_2.2.0_linux_amd64.tar.gz
$ tar -xvf dalfox_2.2.0_linux_amd64.tar.gz
```

7) run dalfox (linux_amd64)
```
$ ./dalfox version

    _..._
  .' .::::.   __   _   _    ___ _ __ __
 :  :::::::: |  \ / \ | |  | __/ \\ V /
 :  :::::::: | o ) o || |_ | _( o )) (
 '. '::::::' |__/|_n_||___||_| \_//_n_\
   '-.::''

Parameter Analysis and XSS Scanning tool based on golang
Finder Of XSS and Dal is the Korean pronunciation of moon. @hahwul
v2.2.0
```

**Comment by hahwul** [comment]
@d4715 
As you can see from 4 to 7 of the testing log, I think the OS architecture problem is right!
`Change the binary architecture` or try building directly from go (`go get`, `go build`, `go install`) for fix this issue

**Comment by d4715** [comment]
@hahwul,
Thanks for your quick response and guidance i will follow steps provided by
you , if any doubts occur so i will contact you on github .
Thanks & Regards
d4715

**Comment by d4715** [comment]
@hahwul 
first sorry for late reply 
yes you are right at that time i was choose wrong file so after read your previous replay.
i just done this steps and my problem solved 
1)wget https://github.com/hahwul/dalfox/releases/download/v2.2.0/dalfox_2.2.0_linux_amd64.tar.gz
2)tar -xvf dalfox_2.2.0_linux_amd64.tar.gz
3)after that i opened that folder and run this command cp dalfox /root/go/bin/
4)then i just open new terminal run this command dalfox version and version is v2.2.0

thanks for your previous valuable reply 

Thanks & Regards,
@d4715

**Comment by hahwul** [comment]
@d4715 
I'm glad it worked out! I'll close this issue! 
If you have any more questions or problems, feel free to tell me!

Cheers
