### ISSUE TITLE
go install - not working / error loading module requirements

### ISSUE THREAD

**Issue by fromCharCode-git** [hahwul/dalfox#135]
```
go install 
go: finding github.com/ugorji/go/codec v1.1.5-pre
go: github.com/ugorji/go/codec@v1.1.5-pre: unknown revision codec/v1.1.5-pre
go: error loading module requirements
```
github.com/ugorji/go/codec is 404

 go get -u github.com/hahwul/dalfox is working fine

**Comment by hahwul** [comment]
@KeevDesign 
Thank you for submit report! 

The package does not appear to be directly referenced in `go.mod`. I think, it is dependency in other module. Could you install `go/codec` with the order below?

```
$ go get -u github.com/ugorji/go/codec

go: github.com/ugorji/go/codec upgrade => v1.1.13
go: downloading github.com/ugorji/go/codec v1.1.13
go: downloading github.com/ugorji/go v1.1.13
```
https://github.com/ugorji/go

**Comment by KeevDesign** [comment]
Hi again,
for me the optimal form of installation was 
snap install dalfox --devmode 
as there is no issue with it.
Parrot OS x64

You are probably right
github.com/ugorji/go/codec looks like dependency of github.com/ugorji/go/ but I can provide any additional info on this issue as my knowledge of debugging are limited
best regards
