### ISSUE TITLE
Go lang Issuesc 

### ISSUE THREAD

**Issue by mr-malware0x01** [hahwul/dalfox#137]
I am facing the This Issue can help please 
![Screenshot from 2020-10-29 21-20-58](https://user-images.githubusercontent.com/31737729/97598518-14380c00-1a2d-11eb-9f10-48db5d32ed3b.png)

**Comment by DEMON1A** [comment]
Your go version won't work with this tool. you have to delete this version and install go1.15.2+

Use this command to see where you installed go `echo $GOROOT` then delete the go folder. for example `rm -rf /usr/local/go`
After that download go using wget `wget 'https://golang.org/dl/go1.15.3.linux-amd64.tar.gz'` and extract the go folder. `tar -xvf go1.15.3.linux-amd64.tar.gz` and move the extracted go folder into your $GOROOT path. for example  `mv go /usr/local/`. then try to install dalfox again. it should work.

**Comment by hahwul** [comment]
@mr-malware0x01 @DEMON1A 
I recently raised the dependency of go version from `1.14` to `1.15`, and I didn't know this issue would happen. Because it works normally at `1.14`, we modified `go.mod` 😁

Thank you so much for the issues and all the activities!
