### ISSUE TITLE
Arm32 and 64

### ISSUE THREAD

**Issue by phor3nsic** [hahwul/dalfox#145]
Please build binaries for these architectures, when trying to compile it is not possible.

NOTE: I'm trying to use on a raspberry pi...

Thanks

**Comment by hahwul** [comment]
@phor3nsic 
Oh, raspberry-pi. I'll test it out! Thank you for your opinion! 👍🏼
                                                                                                                                                                                                                              
![1414](https://user-images.githubusercontent.com/13212227/98833873-e8337680-2481-11eb-9a38-bf1a9f2be8ed.png)

**Comment by hahwul** [comment]
## memo

add arm flag in goreleaser.yml
```
  goarch:
    - arm
    - arm64
```

reference: https://github.com/goreleaser/goreleaser/issues/36

**Comment by hahwul** [comment]
```
    goarm:
      - 6
      - 7
```

**Comment by hahwul** [comment]
Hello again @phor3nsic 
`v2.2.5` release supports ARM32(6/7) and ARM64. Please check the tag below! 
https://github.com/hahwul/dalfox/releases/tag/v2.2.5

If you have a problem, please open it again. Thank you :D
