### ISSUE TITLE
update GF-patterns 

### ISSUE THREAD

**Issue by MR-pentestGuy** [hahwul/dalfox#147]
hey how can i add my gf patterns i have list of patterns with me

**Comment by hahwul** [comment]
Hi @MR-pentestGuy :D

First, thank you for submit question!
You mean the gf-pattern used for default DOM mining? refer to the code here! 

https://github.com/hahwul/dalfox/blob/c6ce088a8fc7bda4a2d2c79fbc73b5cff2753365/pkg/scanning/entity.go#L4

Oh, but please don't add too many patterns. This can affect scan speed 😁
