### ISSUE TITLE
Lack accuracy, running multiple times

### ISSUE THREAD

**Issue by Liodeus** [hahwul/dalfox#153]
## Describe the bug

Hi,

Testing for XSS using the command `dalfox url http://sudo.co.il/xss/level0.php?email=test --only-discovery`, as example. Running this command multiple times like 10 times, dalfox sometimes finds the "Reflected email param" and sometimes not.

Not found : 

```Parameter Analysis and XSS Scanning tool based on golang
Finder Of XSS and Dal is the Korean pronunciation of moon. @hahwul
[*] Using single target mode
[*] Target URL: http://sudo.co.il/xss/level0.php?email=test
[*] Vaild target [ code:200 / size:253 ]
[*] Using dictionary mining option [list=GF-Patterns] 📚⛏
[*] Using DOM mining option 📦⛏
[*] Start BAV(Basic Another Vulnerability) analysis / [sqli, ssti, OpenRedirect]  🔍
[*] Start static analysis.. 🔍
[*] Start parameter analysis.. 🔍
[I] Found 1 testing point in DOM Mining
[*] Static analysis done ✓
[*] BAV analysis done ✓
[*] Parameter analysis  done ✓
[I] Content-Type is text/html; charset=UTF-8
[*] Finish :D
```
Found it :

```Parameter Analysis and XSS Scanning tool based on golang
Finder Of XSS and Dal is the Korean pronunciation of moon. @hahwul
[*] Using single target mode
[*] Target URL: http://sudo.co.il/xss/level0.php?email=test
[*] Vaild target [ code:200 / size:253 ]
[*] Using dictionary mining option [list=GF-Patterns] 📚⛏
[*] Using DOM mining option 📦⛏
[*] Start BAV(Basic Another Vulnerability) analysis / [sqli, ssti, OpenRedirect]  🔍
[*] Start static analysis.. 🔍
[*] Start parameter analysis.. 🔍
[*] Static analysis done ✓
[I] Found 1 testing point in DOM Mining
[*] BAV analysis done ✓
[*] Parameter analysis  done ✓
[I] Content-Type is text/html; charset=UTF-8
[I] Reflected email param => Injected: /inHTML-none(1)  ,  =  +  ]  <  .  |  :  )  '  (  [  >  "  `  -  ;  {  $  }
    10 line:  Email <b>testDalFox</b> added to mailing 
[*] Finish :D
```

It lack accuracy, dalfox should find the same thing everytime. If someone knows why, I'm all ears ;)

## Environment
 * Dalfox Version: v2.2.5
 * Installed from: go-get

**Comment by hahwul** [comment]
Hi @Liodeus 
First of all, thank you for submit issue☺️ I'm testing it, but it's not being reproduced. 
is there any way, could you share the request/response when not reflected param using `--proxy` option?

```
$ dalfox url http://sudo.co.il/xss/level0.php\?email\=test --only-discovery --proxy http://127.0.0.1:8080
```

127.0.0.1:8080 => `burp` or `zap` or `hetty` or other proxy tools

[ e.g ]
![1414](https://user-images.githubusercontent.com/13212227/100757176-62c43600-3431-11eb-860e-0fabe6ee6f02.png)

If there is a detection-related phrase (DalFox) in the response and it is not detected, I think it is false positive. we need a test.

**Comment by hahwul** [comment]
Hello again @Liodeus 
Well, can I see some of the requested data with a proxy? I don't know what conditions/environment doesn't work. (it's hard to know because it's the same result in my environment).

There's a lot of possibilities. A defect in the undiscovered Dalfox or characteristic of the target service (e.g., different LB controls by country, typically AWS region, etc...).
