### ISSUE TITLE
What 'Type is 'application/json;charset=UTF-8', It does not test except customized payload (custom/blind)' mean?

### ISSUE THREAD

**Issue by pdelteil** [hahwul/dalfox#159]
## Question
What I understand from the output message is that the target is receiving JSON inputs and I need to create a custom payload to attempt a XSS attack? 

How can I do this? 

```[I] Found 0 testing point in DOM Mining
[*] Static analysis done ✓
[*] Parameter analysis  done ✓tines 
[*] BAV analysis done ✓ing routines 
[I] Content-Security-Policy is frame-ancestors 'self'
[I] X-Frame-Options is SAMEORIGIN
[I] Strict-Transport-Security is max-age=31536000
[I] Content-Type is application/json;charset=UTF-8
[*] Generate XSS payload and optimization.Optimization.. 🛠
[*] Type is 'application/json;charset=UTF-8', It does not test except customized payload (custom/blind).
[*] Start XSS Scanning.. with 0 queries 🗡
[*] Finish :D
```

## Environment
 * Dalfox Version: 
 * Installed from: (e.g go-get/snapcraft/homebrew)

**Comment by hahwul** [comment]
Hi @pdelteil 
Sorry for late reply and thank you for submit issue!

dalfox check at content-type and scans only for types that can be triggered XSS. Typically, if the content-type is `application/json`, it is not possible to trigger on the actual browser.
