### ISSUE TITLE
Dalfox crashes with 'oncurrent map writes' error

### ISSUE THREAD

**Issue by pdelteil** [hahwul/dalfox#160]
## Describe the bug
Dalfox crashes with 'oncurrent map writes' error

![Screenshot from 2021-01-05 00-32-52](https://user-images.githubusercontent.com/20244863/103608914-4e290100-4efb-11eb-8bb5-0b252eeb1990.png)

## Environment
 * Dalfox Version: 2.2.6
 * Installed from: go-get

**Comment by hahwul** [comment]
Hi @pdelteil ,
Thank you for submit issue :D
Is there any way could you share the URL that I can test?

**Comment by hahwul** [comment]
When writing the params value, it is controlled so that it is not interfered with through mutex.lock unlock, but that part is missing in 762 line. (I declared it after line...)

```
						for k, v := range tempSmap {
							smap = smap + "/" + k + "(" + strconv.Itoa(v) + ")"
						}
						params[k] = append(params[k], smap)
						var wg sync.WaitGroup
						mutex := &sync.Mutex{}
```
https://github.com/hahwul/dalfox/blob/8fd67fbbe73bfc52aa65d860440135c7421b8fe1/pkg/scanning/scan.go#L762

**Comment by hahwul** [comment]
Fixed in version `2.2.7` If there is a problem, please reopen it. 

update
```
$ go get -u github.com/hahwul/dalfox
```

**Comment by pdelteil** [comment]
Thanks a lot !

**Comment by pdelteil** [comment]
Hey there @hahwul I'm trying to do some testing but I couldn't get the reason for the crash even using the debug flag: 

`dalfox file ~/results/input.dalfoxtxt --skip-grepping -o ~/results/output.dalfox.txt -w 200 --debug`

Using that command  I got the regular output on the file.

**Comment by pdelteil** [comment]
This error is still present on my executions.

**Comment by hahwul** [comment]
Hello again @pdelteil ,
I will reopen it and re-examine the issue :D

**Comment by ocervell** [comment]
@hahwul just ran over this today with the latest version

**Comment by fuomag9** [comment]
This happened today too

**Comment by malvinval** [comment]
the problem still exist now.
fatal error: concurrent map writes
fatal error: concurrent map read and map write
