### ISSUE TITLE
how

### ISSUE THREAD

**Issue by Kalimon12** [hahwul/dalfox#161]
whay payload list not work

root@kali:~# dalfox url http://testphp.vulnweb.com/search.php?test=query --custom-payload bypass-xss.txt --only-custom-payload --skip-mining-all --skip-bav
 
    _..._
  .' .::::.   __   _   _    ___ _ __ __ 
 :  :::::::: |  \ / \ | |  | __/ \\ V / 
 :  :::::::: | o ) o || |_ | _( o )) (  
 '. '::::::' |__/|_n_||___||_| \_//_n_\                           
   '-.::''

Parameter Analysis and XSS Scanning tool based on golang
Finder Of XSS and Dal is the Korean pronunciation of moon. @hahwul
[*] Using single target mode
[*] Target URL: http://testphp.vulnweb.com/search.php?test=query
[*] Vaild target [ code:200 / size:4732 ]
[*] Start parameter analysis.. 🔍
[*] Start static analysis.. 🔍
[*] Parameter analysis  done ✓
[*] Static analysis done ✓
[I] Content-Type is text/html; charset=UTF-8
[*] Generate XSS payload and optimization.Optimization.. 🛠
[*] Type is 'text/html; charset=UTF-8', It does not test except customized payload (custom/blind).
[*] Added your 1997 custom xss payload
[*] Start XSS Scanning.. with 0 queries 🗡
[*] Finish :D

**Comment by hahwul** [comment]
Hi @Kalimon12 ,
First thank you for submit issue 😁

I just tested it, and the problem was reproduced. I'll investigate it quickly and patch it when it's fixed! Thank you so much for the tip-off!

**Comment by hahwul** [comment]
```go
if (isAllowType(policy["Content-Type"]) && !options.OnlyCustomPayload){
   //... snip ... make paylaods
} else {
   printing.DalLog("SYSTEM", "Type is '"+policy["Content-Type"]+"', It does not test except customized payload(custom/blind).", options)
}
```

**Comment by hahwul** [comment]
Hello again @Kalimon12 
Oh, I found the cause. Dalfox is basically conducting a test on the reflected value. This url was not tested because there were no parameters that were reflected. 

First of all, it's a spec, but I'll create one additional feature (forced option to scan whether or not it's preflected)

e.g 
```
--force-scan
```
