### ISSUE TITLE
Execution of Bash scripts after detecting something

### ISSUE THREAD

**Issue by rohitcoder** [hahwul/dalfox#170]
Hi @hahwul ,

Really nice work! :)

I was thinking if there is the possibility to implement, kind of alert functionality which we use in sqlmap.

So, what it does is whenever something is detected using sqlmap it triggers our bash script (from where we can automate most of the parts)

In dalfox we need to implement a --alert which will be triggered after dalfox detects something.

It would work something like this
``dalfox file urls.txt --alert="sh ba.sh"``
or 
``dalfox file urls.txt --alert ba.sh``

**Comment by rohitcoder** [comment]
After further research, I found this functionality is already available and works as intended, closing this issue on my own :)

Again thanks for this awesome tool :)

**Comment by ifconfig-me** [comment]
Hi Rohit, can please be more specific?, which functionality are you pointing at?

thanks~
