### ISSUE TITLE
Always set "Accept" header to text/html as on common browsers

### ISSUE THREAD

**Issue by rotemreiss** [hahwul/dalfox#174]
I ran into a case where I was able to trigger a simple reflected XSS manually, but when scanned with DalFox, it wasn't found, due to an error on "Content-Type: text/plain", as in the below screenshot:

![image](https://user-images.githubusercontent.com/9288082/106397712-649d7c00-6417-11eb-80cf-7b7b956295a8.png)

I tried to think what is the difference between the request from the browser that gets the response content-type: text/html and the request from DalFox, and then I figured out that Chrome sends the Accept header as well, and that was actually the difference.

The application I tested regulary responded with the header "Content-Type: text/plain" which isn't vulnerable to XSS in most common browsers, but when sending the `Accept: text/html` header, the response was returned with `Content-Type: text/html`.

So, the solution with DalFox was to add `-H "Accept: text/html"` to the test, and the reflected XSS was detected.

I don't see any reason why not to send it with all the requests, just like Chrome does.
I will be happy to create the PR for this if you need my help with that :)

Thanks.

**Comment by hahwul** [comment]
Hi @rotemreiss 
Thank you for submit issue and sorry to late 😭

I understood what you said. It seems more appropriate to add the Accept header because it is a basic header. 
I'd appreciate it if you could Pull-Request. (If it's difficult, I'll add it. tell me 😁)
