### ISSUE TITLE
Adjust XSS injection phase for targets that reflected all injections

### ISSUE THREAD

**Issue by rotemreiss** [hahwul/dalfox#175]
Let's start with a short background...
I ran a DalFox scan against 200+ URLs, and it was still running a few hours later when I went to sleep. To my surprise, it was still running **on the same target** in the morning.
The step that was running (slow) is:
```
[*] Generate XSS payload and optimization.Optimization.. 🛠
[*] Start XSS Scanning.. with 20625 queries 🗡
 ◢  Queries(7706 / 20625), URLs(35 / 295) :: Testing "unsubscribe_token" param with 100 worker ^C
```

I wondered what is it all about, and I think that the answer is simple.
On some applications, the server reflects whatever parameter you give it, and therefore when DalFox found 26 parameters from mining-DOM + the regular scan list from https://github.com/hahwul/dalfox/blob/30c0821d0d33d3dc8088129069ec325718e4bba2/pkg/scanning/entity.go#L6 (55 params I think) - it ends up with a big amount of parameters to test.

I think that DalFox needs to check if a specific threshold of params is injected (e.g. all params, or even something less strict like 90%, although it will be weird if not all are reflected), and then **only scan one of the injected params** which will give a good picture of the target, if it is vulnerable or not.

Let me know what you think, and I'll be happy to contribute some code if you need my help, although Go isn't my strongest language ;)

**Comment by hahwul** [comment]
Hello again @rotemreiss 
Yes, you are right. this is a problem that I was aware of. There have been cases where the scan speed has slowed sharply since the number of mining parameters was increased recently. 

I haven't been able to work because I've been busy lately, so I'll take the time to work on it. PR is welcome, as always. 
I'll tell you before I work on it!

**Comment by hahwul** [comment]
and please let me know if you want to add it. We recommend that you avoid duplicate operations!

**Comment by rotemreiss** [comment]
Hi @hahwul,
So actually I looked into the code (and as I said, Go isn't where I shine), and I think that it is a bit complicated to implement it without losing some true-positives in the process, and I'll try to explain what I have in mind.

## The implementation in a human language
### First approach
1. Add a new param at the beginning of the mining, with a name that we shouldn't actually meet in the real-world
2. Make a request to the application and see if it reflects in the response
3.1. If not - business as usual, do not make any further changes to the existing functionality
3.2. Yes - check where exactly it reflects and mark those places as places to ignore. This is the hard part since we will want to ignore only on this/those lines and with the specific injection type(s).
Even if we will choose to go with the granularity of a line and not an element, we may still miss real reflections of other params in the same line, but in another element.
I don't think that there will be an easy way to identify the specific element, so maybe we should compromise on inject type (e.g. `inATTR-double(1)/inHTML-none(1)`), and line number

### Second Approach
1. Leave everything as is and count the number of findings from the mining after the mining was done
2. Check if all the params appear in the mining and with the same injection types (e.g. `inATTR-double(1)/inHTML-none(1)`)
3. If yes - remove all those results from the mining results

## Translation to code of the first solution
1. The relevant place for our code is `scan.go`.
2. After line 642 (`if options.Mining {`) we will want to add our own param with a unique name that there's no chance to actually see in the real-world, like `dalfoxsecretparam`. Something like: `p.Set("dalfoxsecretparam", "")`
3. Save the line number+injection type in a variable, and match it against all further mining findings with other param names, if there is an exact match - do not save the param as a successful mining param.
This should be added around line 750 - `pointer := optimization.Abstraction(resbody, "DalFox")`

Please let me know what you think.
I really want to see it in DalFox, so I can try to invest a few more hours on that, although you will probably be much more efficient here.

**Comment by hahwul** [comment]
@rotemreiss 
Thank you very much for your good opinion. I think first and second are both very good ideas. Personally, I'm more interested in first. If you deliver special parameters that do not overlap, and if those parameters are reflected, add only those parameters without processing the other parameters, the unnecessary mining will be reduced, and will be testing(without missing reflected param)

And In fact, there are sections where similar tricks were used 😅
https://github.com/hahwul/dalfox/blob/master/pkg/scanning/scan.go#L43

Let me know if you have any disagreements! If not, I'll go ahead and develop it! (If you want to develop that part, let me know!)
