### ISSUE TITLE
Write scanning URL address and number before each scan in multi mode

### ISSUE THREAD

**Issue by M4Mahdi** [hahwul/dalfox#202]
I was confuse after multi URL(task) insertion through pipe.
There is no URL address and URL number(number of line in the inserted file) as header for each scan in the terminal.
Please add this.
Thank you.

**Comment by hahwul** [comment]
Hi @M4Mahdi 
Recently, there was a correction in the logger, and i think my mistake it. I'll develop it right away and let you know as soon as it's patched

**Comment by hahwul** [comment]
## Testing
![1414](https://user-images.githubusercontent.com/13212227/108612762-0c163900-742f-11eb-9eac-13c5a1b64245.jpg)

@M4Mahdi 
If there is a shortage or problem, please open it again and let me know!
