### ISSUE TITLE
SAMEORIGIN

### ISSUE THREAD

**Issue by yashanand** [hahwul/dalfox#204]
I think the tool stops testing XSS if it gets the X-Frame-Header.
![image](https://user-images.githubusercontent.com/21155589/109396801-41ec7d80-7959-11eb-9617-7efd3befdc60.png)

https://wallpaperaccess.com/search?q=%3C/title%3E%3Cscript%3Ealert(1)%3C/script%3E

**Comment by hahwul** [comment]
Hi @yashanand 
Thank you for submit issue!
I checked this, the target site appears to be blocking it.

![1414](https://user-images.githubusercontent.com/13212227/109502353-34abcc00-7adc-11eb-8b7a-7633f8d39f6a.jpg)

It is not accurate, but blocked if a large number of requests occur in a short time.
To avoid these cases, it is recommended that you adjust the number of workers to slow down, or scan in an environment where IP is not specific, such as torsocks.

e.g 
```
$ torsocks dalfox url https://wallpaperaccess.com/search\?q\=asdf
```
```
$ dalfox url https://wallpaperaccess.com/search\?q\=asdf -w 1
```

No logic branches based on `x-frame-option`. (Just providing information)

**Comment by hahwul** [comment]
@yashanand 
It seems that it is not a development issue, so I close it. If you need more help, please use the [discussions](https://github.com/hahwul/dalfox/discussions)!
