### ISSUE TITLE
Scan XSS CVE

### ISSUE THREAD

**Issue by hahwul** [hahwul/dalfox#206]

**Comment by lucmichalski** [comment]
bump +1 for magento and prestashop

**Comment by hahwul** [comment]
@pdelteil 
Oh, I missed the comment. sorry..  Yes, match what I thought. But I haven't thought about it in detail yet, so I'm not sure if it'll be possible to implement it well 🤔

**Comment by lucmichalski** [comment]
@hahwul 

maybe you should create or import nuclei templates https://github.com/projectdiscovery/nuclei-templates

just an idea :-)

**Comment by hahwul** [comment]
@lucmichalski 
Thank you! I'll keep that in mind.
