### ISSUE TITLE
how to provide blind xss payload -b  payload.xss.ht or -b http://payload.xss.ht

### ISSUE THREAD

**Issue by balook** [hahwul/dalfox#220]
## Question
how to provide blind xss payload -b  payload.xss.ht or -b http://payload.xss.ht
## Environment
 * Dalfox Version: 
 * Installed from: (e.g go-get/snapcraft/homebrew)
how to provide blind xss payload -b  payload.xss.ht or -b http://payload.xss.ht

**Comment by ifconfig-me** [comment]
You can use both.
