### ISSUE TITLE
dalfox command not found

### ISSUE THREAD

**Issue by awais922609** [hahwul/dalfox#221]
## Question
I am not getting that i have installed this multiple times using github by same process given by you but still it gives the same error that dalfox command not found. Please hellp me regarding this issue..
## Environment
 * Dalfox Version: upto date 
 * Installed from: git clone https://github.com/hahwul/dalfox 
 * cd dalfox 
 * go build
![image_2021-04-19_124937](https://user-images.githubusercontent.com/69464258/115200472-b3e97380-a10d-11eb-82a2-5decf175a7a7.png)

**Comment by ZorD1** [comment]
It's not a problem with dalfox but you haven't added the path where go stores the compiled binaries to the PATH yet.

Add this to the .bashrc or .zshrc file
# Golang vars
export GOROOT = / usr / local / go
export GOPATH = \ $ HOME / go
export PATH = \ $ GOPATH / bin: \ $ GOROOT / bin: \ $ HOME / .local / bin: \ $ PATH

**Comment by awais922609** [comment]
Thanks alot for your help.

**Comment by Wicakweee23** [comment]
I've try that.. but it doesn't work :(
But I can check my go version. 

`go version go1.19.6 linux/amd64`                  
`dalfox: command not found`

I'm having the same issue, I can't run dalfox..
My thanks for helping me

**Comment by hahwul** [comment]
@Wicakweee23 
Hi! How did you install it? hombrew? or go install?
Could you check if there is a dalfox binary in the directory below?

- `/opt/homebrew/bin/dalfox` if you install with `brew install (homebrew)`
- `~/go/bin/dalfox` if you install with `go install`

**Comment by Wicakweee23** [comment]
> @Wicakweee23 Hi! How did you install it? hombrew? or go install? Could you check if there is a dalfox binary in the directory below?
> 
>     * `/opt/homebrew/bin/dalfox` if you install with `brew install (homebrew)`
> 
>     * `~/go/bin/dalfox` if you install with `go install`

I installed it by Go install, my go version is go1.19.6. Yes, there is a dalfox binary in the directory go/bin/.

**Comment by haarissabir** [comment]
> > @Wicakweee23 Hi! How did you install it? hombrew? or go install? Could you check if there is a dalfox binary in the directory below?
> > ```
> > * `/opt/homebrew/bin/dalfox` if you install with `brew install (homebrew)`
> > 
> > * `~/go/bin/dalfox` if you install with `go install`
> > ```
> 
> I installed it by Go install, my go version is go1.19.6. Yes, there is a dalfox binary in the directory go/bin/.

I am having the same error. If you have resolved it by any chance. Please help. Any help would be appreciated
![Screenshot 2023-06-01 015644](https://github.com/hahwul/dalfox/assets/63015359/41e19bd7-3fe3-4093-a5ff-b088fa1744ea)
. Thankyou

**Comment by lalit97-98** [comment]
had same issues so i installed with another method  ...
![dalfox](https://github.com/hahwul/dalfox/assets/73432386/daf14235-8f0f-4824-9425-1a1c8831d435)

**Comment by rengoku6513** [comment]
> had same issues so i installed with another method ... ![dalfox](https://user-images.githubusercontent.com/73432386/253739422-daf14235-8f0f-4824-9425-1a1c8831d435.JPG)

Thankss it works !
