### ISSUE TITLE
Trigger paramter does not work

### ISSUE THREAD

**Issue by OttFH** [hahwul/dalfox#222]
## Describe the bug
The `--trigger` parameter does not get set to options correctly.

## Environment
 * Dalfox Version: 2.3.7
 * Installed from: docker hub and build source code

I do not know much about golang but I added some logging to sxss.go and ran it with the provided [example](https://github.com/hahwul/dalfox/blob/master/docs/_docs/modes/sxss-mode.md):
```
package cmd

import (
	"fmt"
	"github.com/hahwul/dalfox/v2/pkg/printing"
	"github.com/hahwul/dalfox/v2/pkg/scanning"
	"github.com/spf13/cobra"
)

var trigger string
var sequence int
var mass bool

// sxssCmd represents the sxss command
var sxssCmd = &cobra.Command{
	Use:   "sxss [target] [flags]",
	Short: "Use Stored XSS mode",
	Run: func(cmd *cobra.Command, args []string) {
		fmt.Println("start trigger:", trigger)
		fmt.Println("start options trigger:", options.Trigger)
		printing.Banner(options)
		printing.Summary(options, args[0])
		if len(args) >= 1 {
			printing.DalLog("SYSTEM", "Using Stored XSS mode", options)
			scanning.Scan(args[0], options, "Single")
		} else {
			printing.DalLog("ERROR", "Input target url", options)
			printing.DalLog("ERROR", "e.g dalfox sxss https://google.com/?q=1 --trigger https://target/profile", options)
		}
	},
}

func init() {
	rootCmd.AddCommand(sxssCmd)

	//Str
	sxssCmd.PersistentFlags().StringVar(&trigger, "trigger", "", "Checking this url after inject sxss code (e.g --trigger https://~~/profile)")
	fmt.Println("init trigger:", trigger)

	//Int
	sxssCmd.PersistentFlags().IntVar(&sequence, "sequence", -1, "Set sequence to first number (e.g --trigger https://~/view?no=SEQNC --sequence 3)")

	//Int
	sxssCmd.PersistentFlags().BoolVar(&mass, "mass", false, "Testing mass vector (coming soon)")

	options.Trigger = trigger
	options.Sequence = sequence
	options.Mass = mass
}
```
![grafik](https://user-images.githubusercontent.com/48800240/116120156-86796880-a6bf-11eb-948e-3e5c30404a54.png)

**Comment by hahwul** [comment]
Hi @OttFH 
There hasn't been much change in this part... but I'll check it out! Thank you for reporting the issue 😁

**Comment by hahwul** [comment]
Hi @OttFH 
I found a problem while processing command in sxss mode and solved it. First of all, it's only applied to the development version, so please test it and let me know if there's anything wrong.

## How to update dev version
```
$ GO111MODULE=on go get -v github.com/hahwul/dalfox/v2
```

or 

```
$ git clone https://hahwul/dalfox
$ cd dalfox
$ go build
$ ./dalfox
```

If there are no special issues, it will be inclueded in the next release 😁

**Comment by hahwul** [comment]
@OttFH 
First of all, when I tested it, there was no problem, so I close the issue. If there is a problem, please reopen it 😎
