### ISSUE TITLE
Dalfox Error

### ISSUE THREAD

**Issue by Krosskid12** [hahwul/dalfox#228]
![image](https://user-images.githubusercontent.com/73221787/118526185-b74d3a80-b75f-11eb-95a4-513cf1ca6526.png)
Dk why this is happening.

**Comment by hahwul** [comment]
Hi @Krosskid12 
Thank you for submit issue.
Um.. first, Is it mobile ssh or VPS? Similar errors may occur when the cli processes dynamic graphic elements, such as spinner and progress bar.

https://github.com/hahwul/dalfox/issues/104

If you are uncomfortable, you can skip the spinner with option `--no-spinner` first.

e.g
```
$ dalfox url http://testphp.vulnweb.com/listproducts.php\?artist\=123 --no-spinner
```

**Comment by hahwul** [comment]
@Krosskid12 
This was not an easily modifiable issue, if i remember to correctly 😭
I need to roll up our sleeves. for fix

**Comment by Krosskid12** [comment]
Hii i am using it in VPS

**Comment by hahwul** [comment]
Hello again @Krosskid12 
Ah.. this is the issue I was thinking of........😭 
Please use option `--no-spinner` for now. I don't know if it's possible, but I'll find more solution!

**Comment by hahwul** [comment]
@Krosskid12 
Let me know if you have the same problem using `--no-spinner`!

**Comment by Krosskid12** [comment]
![image](https://user-images.githubusercontent.com/73221787/119607264-b5e0d980-be13-11eb-9128-05f9082f207f.png)
got same when trying mass urls

**Comment by hahwul** [comment]
Hi @Krosskid12 😁
I fixed a bug where spinners were output even when `--mass` and `--no-spinner` were used at the same time.

![](https://user-images.githubusercontent.com/13212227/119818129-c97e6400-bf29-11eb-90ce-e6950201130c.png)
*left: developement version / right: released version*

First of all, please test to see if it works in the following way.
```
$ git clone https://github.com/hahwul/dalfox
$ cd dalfox 
$ go build 
$ ./dalfox ~~
```

To update with `go-get`, you have to select to the latest version to update to the modified version. There is still some work left for the official release, so wait!

**Comment by hahwul** [comment]
Related link
* https://twitter.com/hahwul/status/1300481659595182081
* https://github.com/hahwul/dalfox/issues/104
