### ISSUE TITLE
Pipe mode lowercases URLs

### ISSUE THREAD

**Issue by davidh-test** [hahwul/dalfox#238]
## Describe the bug
When used in pipe mode, upper case letters in URLs are replaced with lower case letters. 

Example:
```
cat UPPERlower.txt
https://192.168.7.240/UPPERlower.cgi

cat UPPERlower.txt | ./dalfox pipe 2>&1 | grep URL
[*] 🦊 Start scan [SID:0][0/1][0.00%%] / URL: https://192.168.7.240/upperlower.cgi
```

Note how the cgi's name has been modified.

The file and url modes preserve the URL:
```
./dalfox file UPPERlower.txt 2>&1 | grep URL
[*] 🦊 Start scan [SID:0][0/1][0.00%%] / URL: https://192.168.7.240/UPPERlower.cgi

./dalfox url "https://192.168.7.240/UPPERlower.cgi" 2>&1 | grep URL
[*] 🦊 Start scan [SID:Single] / URL: https://192.168.7.240/UPPERlower.cgi
```

If this isn't a bug, I'd appreciate some help using pipe mode with mixed case URLs, thanks.

## Environment
 * Dalfox Version: v2.3.7-64-gf5faf14
 * Installed from: github, running on Centos7 with go1.15.5

**Comment by hahwul** [comment]
Hi @davidh-test 
First, thank you for submit issue!
I reproduced and solved the problem right away. You can check the immediately in dev version, and the official release will be reflected in 2.4.0. (within June)
