### ISSUE TITLE
--found-action not working in alpine

### ISSUE THREAD

**Issue by phor3nsic** [hahwul/dalfox#244]
## Describe the bug
```
~/go/bin/dalfox url http://testphp.vulnweb.com/listproducts.php\?cat\=123\&artist\=123\&asdf\=ff --found-action="echo test >> test.txt"

[G] Found dalfox-error-mysql5 via built-in grepping / payload: toOpenRedirecting
[E] execution error from found-action
    check the manual that corresponds to your MySQL server version
```

I'm trying to run in an [alpine](https://hub.docker.com/_/alpine) container, everything works fine, only the --found-action doesn't work!

## Environment
 * Dalfox Version: v2.4.2
 * Installed from: (e.g go-get)

**Comment by phor3nsic** [comment]
Hi, I detected the problem, this is due to alpine not having pre installed bash, only sh

**Comment by phor3nsic** [comment]
https://github.com/hahwul/dalfox/blob/1f32f3494e1aa3312f84b3e2a836eb61a9ae9aac/pkg/scanning/foundaction.go#L18

**Comment by hahwul** [comment]
Hi @phor3nsic 
Thank you very much for finding the problem. I'll make a patch!

In my opinion, there will be two ways. provide so that users can choose shell application(sh, bash, zsh, etc), or to process it through execute commands without using a separate shell. Personally, the latter would be cool, but I'll find out if it's easy.

**Comment by hahwul** [comment]
@phor3nsic 
(If I remember correctly, I think it was handled like that because of the factor arguments issue of exec.Command😅)

**Comment by hahwul** [comment]
## memo
Check running shell
```
$ echo $0
/usr/bin/zsh
```

Test in dalfox
```
$ dalfox url https://xss-game.appspot.com/level1/frame --found-action="echo $0 > l"
$ cat l 
/usr/bin/zsh
```

**Comment by hahwul** [comment]
## Test `-c` flag
zsh
```
zsh -c uname 
Linux
```
sh
```
sh -c uname 
Linux
```

bash
```
$ bash -c uname
Linux
```

All commonly used shells support the -c flag.

**Comment by hahwul** [comment]
@phor3nsic Hello again!
I added `--found-action-shell` flag, it is select shell application for found action. 

e.g 
```
$ dalfox url http://testphp.vulnweb.com/listproducts.php\?cat\=123\&artist\=123\&asdf\=ff \
--found-action "echo '@@query@@' > data" \
--found-action-shell=sh
```

```
$ dalfox url http://testphp.vulnweb.com/listproducts.php\?cat\=123\&artist\=123\&asdf\=ff \
--found-action "echo '@@query@@' > data" \
--found-action-shell "/bin/zsh"
```

Actually, I was going to selected shell it automatically, but there were more restrictions than I thought. First, I'll add this flag and test it out later! Thank you so much for helping me improve! The release will be this evening (in about five hours ...?? )! Refer.

Please reopen if there is any problem :D
