### ISSUE TITLE
Documentation on JSON output values

### ISSUE THREAD

**Issue by kmcquade** [hahwul/dalfox#260]
## Question

@hahwul - do you have documentation on what the different values in this JSON output mean - specifically `type` and `evidence`? For example, I've seen `type` be either `Grep` or `inHTML` but it's not clear what this indicates and how it can help the developer identify the issue or root cause. Would be nice to get a definition.

Similarly, for `evidence`, I've seen either `dom verify` or `BUILT-IN`. This seems like something related to the internals of the application. Can we get a list of the possible values here, and a definition?

## Environment
 * Dalfox Version: v2.4.8
 * Installed from: Homebrew

**Comment by hahwul** [comment]
Hello again! @kmcquade 
No, I haven't documented it yet. It's not complicated, so I'll add it to Docs before the next release! 
Thank you for your opinion :D

**Comment by kmcquade** [comment]
Fantastic! Thank you 😃
