### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Kalimon12** [hahwul/dalfox#269]
how speed up scan xss only

**Comment by hahwul** [comment]
Hi @Kalimon12 
The most influential factor for speed is the use of headless browsers. You can use the A flag to stop using headless to speed up the scan, but it is inversely proportional to the probability that you can detect.

```
 --skip-headless               Skipping headless browser base scanning[DOM XSS and inJS verify]
```

e.g
```
$ dalfox url https://xss-game.appspot.com/level1/frame --skip-headless
```

Other than this, increase the number of workers to achieve more concurrency. 
```
-w, --worker int                  Number of worker (default 100)
```

or to scan multiple hosts at the same time with the option(pipe/file mode) `--mass`.

```
$ dalfox file urls.txt --mass
```
