### ISSUE TITLE
Parameter option not respected

### ISSUE THREAD

**Issue by IamLunchbox** [hahwul/dalfox#275]
## Describe the bug
The `-p` flag seems to be not respected in conjunction with the `-d` parameters.    
      
Maybe a niche problem:      
I tried to test a specific POST-Parameter, e.g. an unsafe e-mail field, with the `-p` flag. Since the specific website needs extra data in the POST-Request, e.g. `message`, `-d message=test` is used. 

The argument therefore is `./dalfox url -F -X POST -d "message=test&email=test" --param email https://example.org`. Dalfox then starts to check the webpage and begins to test **all** possible input-vektors - `message` as well even though that vektor should remain static.

## Environment
 * Dalfox Version: v2.4.9
 * Compiled with go version `go1.15.15 linux/amd64`

**Comment by hahwul** [comment]
@IamLunchbox 
First, thank you so much for submit issue!
An omission of the `optimization.CheckUniqParam` function was found and added to verify uniqparam in some codes (Mining, bav, some xss). 

First of all, it is reflected in the dev branch and will be added to the next release of `v2.5.0`.
