### ISSUE TITLE
"brew tap hahwul/dalfox" throws URL formulae error on M1 Macs

### ISSUE THREAD

**Issue by millsmillsymills** [hahwul/dalfox#285]
Testing on an Intel Mac:
`brew tap hahwul/dalfox` - Success
`brew install dalfox` - Success

M1 Mac:
`brew tap hahwul/dalfox`  - Fail with
`Error: Invalid formula: /opt/homebrew/Library/Taps/hahwul/homebrew-dalfox/Formula/dalfox.rb
formulae require at least a URL`
`Error: Cannot tap hahwul/dalfox: invalid syntax in tap!`

**Comment by hahwul** [comment]
@millsmillsymills 
Thank you for submit issue!
When building with goreaser, it is build with arm64, but I don't know the exact cause to problem. 
I'll check

**Comment by hahwul** [comment]
## Memo
* https://stackoverflow.com/questions/66381265/does-the-mongocli-support-a-formula-url-for-apple-m1-chips
```
arch -x86_64 brew tap mongodb/brew 
brew install mongodb-community@4.4  
```

**Comment by hahwul** [comment]
Upgrade 1.16 commit(https://github.com/hahwul/dalfox/commit/257341fba2c4d00b6fdf99f92dde5e1b4381479b)

**Comment by hahwul** [comment]
Hello again @millsmillsymills 
I made patch to version of [v2.5.2](https://github.com/hahwul/dalfox/releases/tag/v2.5.2) for fix this issue. 
Can you test if it's installed well? (I have only intel mac... 😭)

**release log (darwin_arm64)**
```
...
      • building                  binary=/home/devi/tools/dalfox/dist/dalfox_darwin_amd64/dalfox
      • building                  binary=/home/devi/tools/dalfox/dist/dalfox_freebsd_arm_6/dalfox
      • building                  binary=/home/devi/tools/dalfox/dist/dalfox_freebsd_arm64/dalfox
      • building                  binary=/home/devi/tools/dalfox/dist/dalfox_darwin_arm64/dalfox
...
```

**Comment by millsmillsymills** [comment]
Works perfectly, thanks for the quick fix!!
