### ISSUE TITLE
XSS in url

### ISSUE THREAD

**Issue by SAGEof6iixPATHS** [hahwul/dalfox#291]
Hey!

I found out today that dalfox only finds xss in params... not in urls paths.
Like `https://example.com/index.html<script>alert()</script>`
or maybe like `https://example.com/index.html'onerror=alert()'//`

Can you find a way to do that?

**Comment by hahwul** [comment]
Hi @SAGEof6iixPATHS 
First, Thank you for submit Issue :D

Is there an example of response if it is not detected?
Dalfox is also scanning for path-based xss.

![스크린샷 2021-10-01 오후 11 54 27](https://user-images.githubusercontent.com/13212227/135641483-955da828-d598-46b9-8c64-25380f3db08f.png)

**Comment by SAGEof6iixPATHS** [comment]
I am seeing this error when I add a potential vulnerable path...

My command: `dalfox url "http://path.com/path/path/path" -b https://snak3.xss.ht`

``` ⠋  [SA: ✓ PA: ✓ BAV: ✓ ] Waiting for analysis 🔍 panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x60 pc=0x5da2d4]

goroutine 37 [running]:
net/url.(*URL).Query(0xc000f9e4b0)
        /usr/local/go/src/net/url/url.go:1130 +0x14
github.com/hahwul/dalfox/v2/pkg/scanning.ParameterAnalysis.func6(0xc0016fc000, 0xc000192650)
        /root/go/pkg/mod/github.com/hahwul/dalfox/v2@v2.4.8/pkg/scanning/scan.go:1142 +0x8a
github.com/PuerkitoBio/goquery.(*Selection).Each(0xc000195a70, 0xc0007e9530)
        /root/go/pkg/mod/github.com/!puerkito!bio/goquery@v1.7.1/iteration.go:10 +0x46
github.com/hahwul/dalfox/v2/pkg/scanning.ParameterAnalysis({_, _}, {{0x0, 0x0}, {0x0, 0x0}, {0x1b914d8, 0x0, 0x0}, {0x0, ...}, ...}, ...)
        /root/go/pkg/mod/github.com/hahwul/dalfox/v2@v2.4.8/pkg/scanning/scan.go:1138 +0x9d6
github.com/hahwul/dalfox/v2/pkg/scanning.Scan.func3()
        /root/go/pkg/mod/github.com/hahwul/dalfox/v2@v2.4.8/pkg/scanning/scan.go:148 +0xdf
created by github.com/hahwul/dalfox/v2/pkg/scanning.Scan
        /root/go/pkg/mod/github.com/hahwul/dalfox/v2@v2.4.8/pkg/scanning/scan.go:146 +0x1105
```

I tried on phpvulnweb by acunetix but that works well, it ends the script after it scans all the possible ways...

**Comment by hahwul** [comment]
@SAGEof6iixPATHS 
Well, there's an error in the url package of golang. Is it the same problem with the latest version?

* your version: v2.4.8
* latest version: v2.5.3

You can update it yourself and use it, but just in case, I'll share the docker command!

```
docker run -it hahwul/dalfox:v2.5.3 /app/dalfox url "http://path.com/path/path/path" -b https://snak3.xss.ht
```
