### ISSUE TITLE
After update yo last version I got a error when I try use url arg

### ISSUE THREAD

**Issue by xElkomy** [hahwul/dalfox#292]
## Describe the bug
Hello when I try to do anything with `dalfox url http://xss.xss `.

## Environment
 * Dalfox Version: v2.5.2
 * Installed from:  download the repo and build it.
 
the error is
```bash
goroutine 2631 [running]:
github.com/hahwul/dalfox/v2/pkg/scanning.ParameterAnalysis.func7()
        /root/go/src/github.com/hahwul/dalfox/pkg/scanning/parameterAnlaysis.go:202 +0x316
created by github.com/hahwul/dalfox/v2/pkg/scanning.ParameterAnalysis
        /root/go/src/github.com/hahwul/dalfox/pkg/scanning/parameterAnlaysis.go:194 +0xe4c
```

**Comment by hahwul** [comment]
Hi @xElkomy 
First, thank you for submit issue!

Can you update version v2.5.3? The problem has been fixed in that version. If it's have problem in 2.5.3, please let me know 😊

**Comment by xElkomy** [comment]
Ok, I think the issue with the huge requests.

Regards
