### ISSUE TITLE
Some incorrect header parsing occurs in situation when scan file mode with --rawdata 

### ISSUE THREAD

**Issue by hahwul** [hahwul/dalfox#293]
## Describe the bug
SSIA

## Environment
 * Dalfox Version: v2.5.3
 * Installed from: all

**Comment by hahwul** [comment]
Original request
```
Cookie: PHPSESSID=hioibokj2lk3
```


Req in Dalfox
```
Cookie: HPSESSID=hioibokj2lk3
```

**Comment by boundmania** [comment]
thanks bro~

**Comment by hahwul** [comment]
https://github.com/hahwul/dalfox/blob/6a4c9be756011b44188656175495004a43feb27b/cmd/file.go#L41
