### ISSUE TITLE
Dalfox supports login function in web page

### ISSUE THREAD

**Issue by HarryJohnAsir** [hahwul/dalfox#301]
## Question

Web pages usually have login and  some features/urls are available to the user only after login. 
Can you please feedback is there any mechanism to handle login using dalfox, so that web pages/urls after login can be scanned for XSS by dalfox. Thank you.

## Environment
 * Dalfox Version:  v2.5.4
 * Installed from: (e.g go-get/snapcraft/homebrew): go-get

**Comment by hahwul** [comment]
Hi @HarryJohnAsir 
I'm sorry for the late reply. There is no function to process a login flow, but you can add authentication information through the `--cookie`, `--header` option when scanning.

for example
```
$ dalfox url https://google.com --cookie "auth=1234564546;"
$ dalfox url https://google.com --header "X-API-Key: blahblah" --header "SecondHeader: 123444"
```

**Comment by hahwul** [comment]
And even if you scan based on HTTP Raw Request, Dalfox handles authentication headers and so on.

**raw.txt**
```
POST /?q=xspear HTTP/1.1
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:56.0) Gecko/20100101 Firefox/56.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: ko-KR,ko;q=0.8,en-US;q=0.5,en;q=0.3
Connection: keep-alive
Cookie: _ga=GA1.2.1102548207.1555467144; _gid=GA1.2.1362788908.1563875038
X-Auth-Key: abcd1234
Upgrade-Insecure-Requests: 1
Host: www.hahwul.com

asdf=asdf
```

```
$ dalfox file raw.txt --rawdata --proxy http://localhost:8090
```

**localhost:8090**
![Screenshot_20211115_221942](https://user-images.githubusercontent.com/13212227/141788963-633bc452-35a4-4931-87ae-5395af958367.jpg)
