### ISSUE TITLE
Dalfox API takes a long time 

### ISSUE THREAD

**Issue by knassar702** [hahwul/dalfox#341]
hello team, I've tried dalfox in `server` mode but it was very slow not like `pipe` mode 
also, I tried to change the worker and delay values but it doesn't make any difference 

best regards

**Comment by hahwul** [comment]
Hi @knassar702 
First, Thank you for submit issue! 
I'll check it out 😊

**Comment by hahwul** [comment]
Hello again @knassar702 
I was testing and found the reason right away! The server mode basically operates the same as the sxss mode. In the [recent v2.7.0 release](https://github.com/hahwul/dalfox/releases/tag/v2.7.0), there was a speed adjustment for the sxss mode. So unlike pipes, it will be slow if you run without any options. 

First of all, it can be solved by increasing the number of workers in options as follows. 

```shell
$ curl -X 'POST' \
  'http://localhost:6664/scan' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "options": {
    "worker": 100
  },
  "url": "http://testphp.vulnweb.com/listproducts.php?cat="
}'
```
=> `[*] [duration: 2.316213911s][issues: 0] Finish Scan!`

And in the next release, v2.7.2, I'll change the mode that the server mode basically looks at to url or pipe!
