### ISSUE TITLE
mass vs multicast?

### ISSUE THREAD

**Issue by gprime31** [hahwul/dalfox#343]
what's the difference?
can both be used at the same time?
why does one or both crash after 300k+ urls? sometimes it makes it to 500k or 1m  every run seems different.  ( 24 cores 128GB ram ) fyi.

**Comment by gprime31** [comment]
arch os
latest go and dalfox.
same with debian-based 
don't think it's OS related.

**Comment by hahwul** [comment]
Hi @gprime31 
First, `--mass` and `--multicast` are the same flags. Initially, it was created as a `--multi-cast` flag, but it was not intuitive, so it was added to use the same flag with the `--mass`.

> --mass == --multicast

If there is a large URLs file, crash is a known issue in the dalfox. I'm still checking this, but I haven't found the exact way yet😭 I'll keep checking 🔥

**Comment by gprime31** [comment]
Ok. Thanks

**Comment by gprime31** [comment]
So what's the max amount of url's in a file you recommend for it not to crash?
