### ISSUE TITLE
[bug] not working with --only-custom-payload flag

### ISSUE THREAD

**Issue by normface** [hahwul/dalfox#344]
## Question
Thanks for great tool. How can i use my custom payload file? I tried the below commands but it didn't work. There is no any requests wity my payloads, i check with Burpsuite. Is it bug?

```
dalfox file target.txt --only-custom-payload --custom-payload ./payloads.txt --skip-bav --skip-mining-all --proxy http://127.0.0.1:8080
/root/go/bin/dalfox file target.txt --custom-payload ./payloads.txt --skip-bav --skip-mining-all --proxy http://127.0.0.1:8080
```

target.txt
```
http://testphp.vulnweb.com/search.php?test=query
http://testphp.vulnweb.com/listproducts.php?cat=
```

payloads.txt
`<script>alert(document.domain)</script>`

![dalfoxOutput](https://user-images.githubusercontent.com/97374392/150586543-c30c8510-c548-4298-8f8c-bb799a037c20.png)

![BurpOutput](https://user-images.githubusercontent.com/97374392/150586556-da022d5f-9f2b-4657-ab4d-7d33ac640ff1.png)

## Environment
 * Dalfox Version: v2.7.0
 * Installed : go install github.com/hahwul/dalfox/v2@latest

**Comment by hahwul** [comment]
Hi @normface 
Thank you for submit issue!
First, when I checked, there seems to be a problem with `--only-custom-payload`. I'll check this out!


## with
```
$ dalfox file target.txt --only-custom-payload --custom-payload ./payloads.txt \
--skip-bav --proxy http://localhost:8090
```

## without 
```
$ dalfox file target.txt --custom-payload ./payloads.txt \
--skip-bav --proxy http://localhost:8090
```

![스크린샷 2022-02-05 오후 12 22 22](https://user-images.githubusercontent.com/13212227/152627074-f22ee821-7b7d-4d13-a97a-e6ff2e4797e8.png)
![스크린샷 2022-02-05 오후 12 22 28](https://user-images.githubusercontent.com/13212227/152627079-160c7f2d-da87-4648-ae86-d5109cfe0d47.png)

**Comment by hahwul** [comment]
@normface 
Hi, I fixed this issue :D
It will be apply in `v2.7.1` release

## Test
```
// payloads.txt
hahwul
```

![스크린샷 2022-02-12 오후 10 17 41](https://user-images.githubusercontent.com/13212227/153712999-06c1d74c-766f-4248-905c-ae974b1792e3.png)

**Comment by hahwul** [comment]
[v2.7.1 release note](https://github.com/hahwul/dalfox/releases/tag/v2.7.1) 🚀
Please refer to the document below for how to update!

https://dalfox.hahwul.com/docs/update/

**Comment by normface** [comment]
Thank you =)
