### ISSUE TITLE
Unable to add multiple cookies 

### ISSUE THREAD

**Issue by archidote** [hahwul/dalfox#346]
## Question

Hi, my question is very simple : 

I want to pass two cookies with the following attributes : 
- PHPSESSID
- security 

to found XSS (post connection) into the following DVWA vuln web app URL : http://192.168.130.128:8081/vulnerabilities/xss_r/?name=fcdsf

So I use these following commands but no one of them worked as I wanted. I supposed that dalfox does not took the second cookie attribute (security) ?

```
./dalfox url http://192.168.130.128:8081/vulnerabilities/xss_r/?name=fcdsf --cookie PHPSESSID=85mvhoi8o64g9d1o1h2dfs3376,security=low --remote-payloads=portswigger
```
OR 
```
./dalfox url http://192.168.130.128:8081/vulnerabilities/xss_r/?name=fcdsf --cookie 'PHPSESSID=85mvhoi8o64g9d1o1h2dfs3376,security=low' --remote-payloads=portswigger
```
OR 
```
./dalfox url http://192.168.130.128:8081/vulnerabilities/xss_r/?name=fcdsf --cookie PHPSESSID=85mvhoi8o64g9d1o1h2dfs3376 --cookie security=low --remote-payloads=portswigger
```

![image](https://user-images.githubusercontent.com/38756128/152142369-240f23ce-97a3-4d16-857f-eb3990095eb8.png)

Thank's for your help 

## Environment
 * Dalfox Version: latest
 * Installed from: docker

**Comment by hahwul** [comment]
Hi @archidote 
`--cookie` flag puts the value in the `Cookie` header as it is. So, to send multiple cookies, you can distinguish them through semicolons, the same as those used on the general web.

```shell
$ dalfox url "http://192.168.130.128:8081/vulnerabilities/xss_r/?name=fcdsf" \
--cookie "PHPSESSID=85mvhoi8o64g9d1o1h2dfs3376; security=low"
```

Let me know if you don't working or if you don't understand it :D

**Comment by archidote** [comment]
Hi @hahwul, 

First of all, thank's for your quickly reply. 

I have tested your command line and it's works perfectly ! 

```
./dalfox url "http://192.168.130.128:8081/vulnerabilities/xss_r/?name=fcdsf" \
--cookie "PHPSESSID=d743ej9ph1ljvmbmqj6j47s7u0; security=low"
```
![image](https://user-images.githubusercontent.com/38756128/152769382-8bffebdb-ad9f-4354-a7f0-cfba2ff5cba2.png)


In fact, the <b> command line need to be strcutured on 2 lines </b>. Otherwise it's not works.

Best regards,
