### ISSUE TITLE
What resource do the workers use?

### ISSUE THREAD

**Issue by LucasCortooms** [hahwul/dalfox#374]
## Question
I can define how many workers I want to use before conducting a scan. Are these workers locally hosted or are they called from a different source? 

## Environment
 * Dalfox Version: latest
 * Installed from: (Snapcraft)

**Comment by hahwul** [comment]
Hi @LucasCortooms 
Local. When scanning, goroutine(high-lightweight threads in golang) interact with each other with multiple task lists, which means the total number of goroutines. So worker is maximum concurrency.

![](https://user-images.githubusercontent.com/13212227/169054807-81c0eb6f-c81d-4d75-8404-3390c66fd5f6.png)

**Comment by LucasCortooms** [comment]
Hi @hahwul 
Thank you for the quick response and clear explanation! 
I understand now have a good day :).

**Comment by hahwul** [comment]
@LucasCortooms 
Enjoy your rest day :D
