### ISSUE TITLE
windows용 글자깨짐 문제

### ISSUE THREAD

**Issue by YongHwan-Jeong** [hahwul/dalfox#392]
안녕하세요.
평소 하울님 블로그 감사히 잘 보고 있습니다 :)
영어를 잘 못해서 한국어로 도움 요청드릴께요..

다름이 아니라, windows 용으로 릴리즈된게 있어서 사용해보려고 하니
cmd 내에서 이미지와 같은 일부 문자는 글자가 깨지는데 도움을 받을 수 있을까요?

아래 명령어를 통해서 utf8로 인코더를 변경해도 해결이 안 되네요.
#chcp 65001
![dalfox_error](https://user-images.githubusercontent.com/67957924/178142147-662d49dc-e8bd-4f59-9df6-1197a6330c97.PNG)

**Comment by hahwul** [comment]
@YongHwan-Jeong 
안녕하세요! `[93m` 같은 데이터는 컬러 값으로 윈도우에서 표기하지 않아서 발생하는 문제로 보입니다. 
우선은.. `--no-color` flag로 색상을 제거할 수 있으니 참고해주시고, 구동 OS에 따라서 자동으로 컬러가 처리되도록 개선해볼게요 :D

```
type domains.txt | dalfox pipe --no-color
```
