### ISSUE TITLE
Include certain messages that are in the command line in the JSON output

### ISSUE THREAD

**Issue by kmcquade** [hahwul/dalfox#422]
Hi, big fan of Dalfox here :) I noticed that there are some really helpful messages in the command line output that are not reflected in the JSON. Some of these could be really helpful in providing context on the vulnerabilities. For example, this part from [pkg/scanning/scan.go](https://github.com/hahwul/dalfox/blob/c344c5842423f76e05e98db99965c504bc413e8b/pkg/scanning/scan.go#L902)

```go
if vStatus[v["param"]] == false {
  printing.DalLog("WEAK", "Reflected Payload in Attribute: "+v["param"]+"="+v["payload"], options)
```

It would be really awesome if we could have the descriptions included in the JSON output! :)

**Comment by hahwul** [comment]
@kmcquade 
Thank you very much for your opinion! 
I'll need some time to think about it, but I'll make it well😉
