### ISSUE TITLE
Optionally include HTTP Request and Response in the JSON output

### ISSUE THREAD

**Issue by kmcquade** [hahwul/dalfox#423]
It would be really helpful if we could optionally have the entire HTTP request and HTTP Response in the JSON output as well. I realize this could become very large but it would be super helpful for providing useful context for the reader. Perhaps as two different options: `--output-request` and `--output-response`.

**Comment by hahwul** [comment]
@kmcquade 
Oh yes, this is really important, too! 
roll up my sleeves. thank you so much :D

**Comment by hahwul** [comment]
@kmcquade 
I'm sorry I'm late! Time went by so fast.. 😭 It will be included in the next version, the 2.9 release. 2.9 is about to be released tomorrow at the earliest, or within this week at the latest! Thank you for the great idea :D

**Comment by kmcquade** [comment]
Amazing! Thank you so much :)
