### ISSUE TITLE
Remote xterm issue

### ISSUE THREAD

**Issue by alfonsocaponi** [hahwul/dalfox#51]
Running dalfox on a remote xterm (with putty client, so without gui) on Ubuntu 18.4 we have a issue with output...

g routines..                         ◒  Waiting routines..
 ◐  Waiting routines.. ed (10 / 38) quries
            ◑  Testing.. (0 / 38) reqs
            ◒  Testing.. (0 / 38) reqs
            ◐  Testing.. (0 / 38) reqs
            ◓  Testing.. (0 / 38) reqs
            ◑  Testing.. (0 / 38) reqs
            ◒  Testing.. (0 / 38) reqs
            ◐  Testing.. (0 / 38) reqs
            ◓  Testing.. (0 / 38) reqs
            ◑  Testing.. (0 / 38) reqs
            ◒  Testing.. (0 / 38) reqs
 ◐  Testing.. (0 / 38) reqs
g routines..                         ◑  Waiting routines..
    ◒  Waiting routines..
g routines..                         ◒  Waiting routines..
 ◐  Waiting routines.. . (0 / 38) reqs
            ◒  Testing.. (0 / 38) reqs
 ◐  Testing.. (0 / 38) reqs
g routines..                         ◓  Waiting routines..
    ◑  Waiting routines..
g routines..                         ◑  Waiting routines..
    ◒  Waiting routines..
g routines..                         ◒  Waiting routines..

**Comment by hahwul** [comment]
Hi @alfonsocaponi ,
Is the actual scan not being processed? I wonder if it's just the output or the scan problem.

**Comment by alfonsocaponi** [comment]
Hi @hahwul, just the output. The scan works fine. I started it and I checked results via logs.
Thank you

**Comment by hahwul** [comment]
Thanks for your reply! I didn't think about the remote xterm environment. First of all, let me create a `--sillent` option! 

Except actual detection data, it not print out as stdout but as stderr. It appears to be a problem that occurred there.

(for support the pipeline)

**Comment by hahwul** [comment]
I updated `--silence` option
a91eb645bed5ccc7372f63951c61d343882d1cd1
