### ISSUE TITLE
Add --delay and --concurrence options

### ISSUE THREAD

**Issue by Sh1Yo** [hahwul/dalfox#52]
As I can see domains with strict rate limit blocks the program.

**Comment by hahwul** [comment]
Thank you for your opinion! I'll add that feature!
```
--delay
--thread
```

I'm thinking of adding a thread option due to the issue below. I think we can limit it to --thread=1 when it's applied.
https://github.com/hahwul/dalfox/issues/46

**Comment by hahwul** [comment]
please update v1.0.2-dev  :D 
```
$ go get -u github.com/hahwul/dalfox
```

**Comment by hahwul** [comment]
i change option name for easy using
`--concurrence` to `-w` , `--worker`
