### ISSUE TITLE
Windows 10 error in dalfox 

### ISSUE THREAD

**Issue by TannicArcher** [hahwul/dalfox#571]
Widnows 10 
dalfox latest from github

Aug 18 14:48:47.705 [DEBU] ['><a href=javas&#99;ript:alert(1)/class=dalfox>click] [vds] false
Aug 18 14:48:47.705 [DEBU] ['><a href=javas&#99;ript:alert(1)/class=dalfox>click] [vrs] false
Aug 18 14:48:47.816 [DEBU] ['><img/src/onerror=.1|alert``>] [vds] false
Aug 18 14:48:47.816 [DEBU] ['><img/src/onerror=.1|alert``>] [vrs] false
Aug 18 14:48:47.839 [DEBU] ['"><iframe srcdoc="<input onauxclick=alert(1)>" class=dalfox></iframe>] [vds] false
Aug 18 14:48:47.839 [DEBU] ['"><iframe srcdoc="<input onauxclick=alert(1)>" class=dalfox></iframe>] [vrs] false
2024/08/18 14:48:49 ERROR: could not unmarshal event: parse error: expected string near offset 687 of 'cookiePart...'
2024/08/18 14:48:50 ERROR: could not unmarshal event: parse error: expected string near offset 645 of 'cookiePart...'
2024/08/18 14:48:50 ERROR: could not unmarshal event: parse error: expected string near offset 643 of 'cookiePart...'

**Comment by hahwul** [comment]
@TannicArcher 
Hello. First of all, I apologize for the late response. 
It seems to be an issue related to [chromedp](https://github.com/chromedp/chromedp); I'll start investigating quickly!

**Comment by TannicArcher** [comment]
> @TannicArcher Hello. First of all, I apologize for the late response. It seems to be an issue related to [chromedp](https://github.com/chromedp/chromedp); I'll start investigating quickly!

It's okay, we are all human, we are all busy with our own things, the main thing is that you noticed the problem.

**Comment by hahwul** [comment]
@TannicArcher 
Could you check if running the binary built from the `dev` branch yields the same result? When [I tested it](https://github.com/hahwul/dalfox/issues/573#issuecomment-2324618349), the error occurred in version 2.9.2, but not in the dev branch. It seems likely that this might be an issue with the chromedp version.

```bash
# Clone
git clone https://github.com/hahwul/dalfox
cd dalfox

# Change branch
git checkout dev

# Build
go build .

# Run
./dalfox ....
```

**Comment by TannicArcher** [comment]
Sorry for the long reply everything works fine without errors
used dev branch 
Thanks for thsi tool:)

**Comment by hahwul** [comment]
@TannicArcher 
Oh, that's really great. Based on this source code, I'll release version 2.9.3. It'll definitely be out by the end of this week.

Thank you once again!
