### ISSUE TITLE
Add --grep option

### ISSUE THREAD

**Issue by hahwul** [hahwul/dalfox#58]
custom grep.
why?
dalfox is xss tool, but it can also be used to find other vulnerabilities.
e.g
- ssti
- information leak
- etc.. 

so, i think need custom grep option

**Comment by hahwul** [comment]
it is last options for release :D

**Comment by bsysop** [comment]
Thats great bro, you should have that, but in case you dont, hope this helps for that or other project.

[patterns.json.txt](https://github.com/hahwul/dalfox/files/4559123/patterns.json.txt)

**Comment by bsysop** [comment]
And my SSTI playroom =]
```
<%= 339 * 431 %>
#{ 339 * 431 }
#{set} ($run=339 * 431) $run
${339*431}
<%=339*431%>
${{339*431}}
{{339*431}}
{{339*'3'}}
[[339*431]]
{{= 339*431 }}
{#339*431}
<# 339*431 >
{@339*431}
${{"{{"}}339*431{{"}}"}}
```

**Comment by hahwul** [comment]
Hi @bsysop 
Thanks dude! Originally, I was going to let the user customize the response grep, but I think some pattern is okay to put it in a built-in pattern. I'll use it well! Thank you.

**Comment by bsysop** [comment]
Gooot it, as you wish bro, you could use it in other tool if you think is better!

**Comment by hahwul** [comment]
`--grep` argument input is the file? regex string..?

and 
Log Format
```
[G] Found via built-in grepping / payload: {339*431} , grep: 146109
    1 line:  146109({"isSuccess":false,"errorMsg":"Parameter error! apps is null","error
    +> https://blahblha!~~~
[G] Found via custom grepping / payload: 'adf , grep: internal_domain://asdf
    1 line:  internal_domain://asdf~~({"isSuccess":false,"errorMsg":"Parameter error! apps is null","error
    +> https://blahblha!~~~
```

**Comment by bsysop** [comment]
Thats awesome, i would love to test that and check new approaches!

**Comment by hahwul** [comment]
Function development is complete, only small pattern addition is required. follow issue below
https://github.com/hahwul/dalfox/issues/60

**Comment by hahwul** [comment]
![1414](https://user-images.githubusercontent.com/13212227/80870778-ab711080-8ce3-11ea-9f43-da9ab9d0297a.png)

**Comment by bsysop** [comment]
Amazing mate!!!! Great job!
