### ISSUE TITLE
Error when execute dalfox

### ISSUE THREAD

**Issue by tXambe** [hahwul/dalfox#77]
Hello,

When I run dalfox

```
dalfox url http://example.com sxss -b https://hahwul.xss.ht
```
I have this error

```
[E] not running Get http://example.com: net/http: request canceled (Client.Timeout exceeded while awaiting headers)

```
Can Anyone help me ?

Thanks and a greeting

**Comment by bsysop** [comment]
Hi @tXambe, lets say `http://example.com` are working, please do a simple command there:

```
curl -i "http://example.com" -H "User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36"
```

and again

```
curl -i "http://example.com"
```


Both worked?

**Comment by hahwul** [comment]
The default timeout for dalfox is 10 seconds. It seems that the connection with the domain takes more than 20 seconds or is not accessible. If the internet is slow, adjust the --timeout option.

```
--timeout int             Second of timeout (default 10)
```

e.g
```
$ dalfox url http://example.com --timeout 60
```

And, sxss cannot be used at the same time because it is a mod like url. To test the sxss, you need to proceed as below.

```
$ dalfox sxss --trigger https://example.com/your_profile https://example.com/save_profile?name=123
```

why?
```
$ dalfox sxss -h

Usage:
  dalfox sxss [target] [flags]

Flags:
  -h, --help             help for sxss
      --mass             Testing mass vector (comming soon)
      --sequence int     Set sequence to first number (e.g --trigger https://~/view?no=SEQNC --sequence 3) (default -1)
      --trigger string   Checking this url after inject sxss code (e.g --trigger https://~~/profile)
```

If you have any more questions, say me :D

**Comment by tXambe** [comment]
Hello,

It already works for me, although it only takes a few seconds to scan it is very strange to me.

Thanks
