### ISSUE TITLE
Problem using file

### ISSUE THREAD

**Issue by ZB83486** [hahwul/dalfox#98]
Hi. I am trying to start dalfox with a file containing all the URLs but unsuccessfully. I have tried almost anything, I always get this output:

[*] Using file mode(targets list)
[*] Loaded 0 target urls

or

[*] Using file mode(targets list)
[*] Loaded 1 target urls
[*] Target URL: /Downloads/domains.txt
[E] not running Get /Downloads/domains.txt: unsupported protocol scheme ""

I am trying dalfox file ./domains.txt or just domains.txt, full path, nothing works. You could probably add that to the readme. What should I do? It's a simple file like:

domains.txt
https://dfds.dfd
https://dghkgsdkjg.dgdsg

etc

**Comment by ZB83486** [comment]
By the way, my version is 2.0.1 from snap.

**Comment by hahwul** [comment]
Hi @ZB83486 ,
Thank you submit issue :D

I'll test it out in the snap version. Is there any way can i check "go get" version is the same result in your env? (If you don't mind, testing please..)

```
$ sudo snap remove dalfox
$ go get -u github.com/hahwul/dalfox
$ ~/go/bin/dalfox file file.txt
```

Cheers,

**Comment by ZB83486** [comment]
Hey,
thanks for such a swift reply.

The version of go should be 1.14 if I checked correctly.
Also, I already have and am trying again to install using `go get -u github.com/hahwul/dalfox` but the thing is I just can't get it do anything. It never loads or logs any output. I just insert the command and nothing, blank terminal log.

**Comment by ZB83486** [comment]
Just tried using docker, and the problem is persistent there as well.

**Comment by hahwul** [comment]
@ZB83486 
Oh? Even at the docker? It's weird.... It's the same image... my image doing great.

Image
```
$ docker images
REPOSITORY                                             TAG                 IMAGE ID            CREATED             SIZE
hahwul/dalfox                                          latest              d84f06e2276b        5 days ago          1.03GB
....
```

Latest?
```
$ docker pull hahwul/dalfox:latest
latest: Pulling from hahwul/dalfox
Digest: sha256:4f27b0a8ce864d337b4e907824423c1c338b2da6474bc6e1a7e80d80b552dae0
Status: Image is up to date for hahwul/dalfox:latest
docker.io/hahwul/dalfox:latest
```


Log
```
root@7dfc634a32ee:/go/src/app# dalfox file samples/sample_target.txt

    _..._
  .' .::::.   __   _   _    ___ _ __ __
 :  :::::::: |  \ / \ | |  | __/ \\ V /
 :  :::::::: | o ) o || |_ | _( o )) (
 '. '::::::' |__/|_n_||___||_| \_//_n_\
   '-.::''

Parameter Analysis and XSS Scanning tool based on golang
Finder Of XSS and Dal is the Korean pronunciation of moon. @hahwul
[*] Using file mode(targets list)
[*] Loaded 2 target urls
[*] Target URL: https://www.hahwul.com/?q=123
[*] Vaild target [ code:200 / size:139294 ]
[*] Start parameter analysis.. 🔍
[*] Start static analysis.. 🔍
[I] Content-Type is text/html; charset=utf-8
[I] Access-Control-Allow-Origin is *
[*] Generate XSS payload and optimization.Optimization.. 🛠
[*] Start XSS Scanning.. with 65 queries 🗡
[*] Finish :D
[*] Target URL: http://testphp.vulnweb.com/listproducts.php?cat=asdf&ff=1
....
```

Sample_target
```
root@7dfc634a32ee:/go/src/app# cat samples/sample_target.txt
https://www.hahwul.com/?q=123
http://testphp.vulnweb.com/listproducts.php?cat=asdf&ff=1
```

Version
```
root@7dfc634a32ee:/go/src/app# dalfox version

    _..._
  .' .::::.   __   _   _    ___ _ __ __
 :  :::::::: |  \ / \ | |  | __/ \\ V /
 :  :::::::: | o ) o || |_ | _( o )) (
 '. '::::::' |__/|_n_||___||_| \_//_n_\
   '-.::''

Parameter Analysis and XSS Scanning tool based on golang
Finder Of XSS and Dal is the Korean pronunciation of moon. @hahwul
v2.0.1
```

**Comment by hahwul** [comment]
@ZB83486 
Looking at this error I'm curious, can you share some of the contents of the domains file?
```
[E] not running Get /Downloads/domains.txt: unsupported protocol scheme ""
```

**Comment by ZB83486** [comment]
Some news: just installed brew too and works perfectly so basically the issue has been resolved which is great but I have no idea what could have been wrong.

**Comment by ZB83486** [comment]
Otherwise it's still the same file, everything, `dalfox file domains.txt`.

**Comment by ZB83486** [comment]
The brew installation really seems to be running fine, no problems so far. Let me know if you want any additional info to the issue, I am really not sure what to think about it. Anyway, thanks for your help and time, I appreciate it a lot!

**Comment by hahwul** [comment]
@ZB83486 
Oh, I'm glad to hear that it works well at homebrew 👍

I'll test it in various environments. In the long run, I think need to add a test logic to solve this problem by automatic testing like github-action. Thank you so much for the issue! If you have another problem, please feel free to tell me 😎
